export enum PathRoutes {
  HOME = '/',
  LOGIN = '/login',
  REGISTER = '/register',
  RESET_PASSWORD = '/reset/password',
  CHANGE_PASSWORD = '/change/password/:link',
  ACTIVATE = '/activate/:link',
  DASHBOARD = '/dashboard',
  STORAGE = '/storage',
  STORAGE_MY_DRIVE = '/storage/my-drive',
  STORAGE_SHARED = '/storage/chared',
  STORAGE_RECENT = '/storage/recent',
  STORAGE_STARRED = '/storage/starred',
  STORAGE_TRASH = '/storage/trash',
  SOCIAL = '/social',
}
